In [1]:
import torch
import torchvision
import gym

import random
import torch.nn as nn
import torch
from torch.autograd import Variable
import torch.autograd as autograd
import torch.nn.functional as F
import gym
import numpy as np
import math
import random
from gym.envs.registration import register
register(
   id='FrozenLakeNotSlippery-v0',
   entry_point='gym.envs.toy_text:FrozenLakeEnv',
   kwargs={'map_name' : '4x4', 'is_slippery': False},
   max_episode_steps=100,
   reward_threshold=0.78, # optimum = .8196
)

env = gym.make('FrozenLakeNotSlippery-v0')
#env = gym.make('FrozenLake-v0')
env.render()



SFFF
FHFH
FFFH
HFFG


In [2]:
score = []
times_trained = 0
times_reach_goal = 0

NUM_EPISODES = 10000000
EPS_START = 0.9
EPS_END = 0.00
EPS_DECAY = 500000
GAMMA = 0.9
ALPHA = 0.2

q_function = []
for s in range(16):
    action_list = []
    for a in range(4):
        action_list.append(0.0)
    q_function.append(action_list)


steps_done = 0
for k in range(NUM_EPISODES):
    done = False
    observation = env.reset()
    #observation, reward, done, info = env.step(env.action_space.sample()) # take a random action
    episode_series = []
    reward = 0
    
    while not done:
        # Get action from pi


        sample = random.random()
        eps_threshold = EPS_END + (EPS_START - EPS_END) * math.exp(-1. * steps_done / EPS_DECAY)
        steps_done += 1
        q_values = np.array(q_function[observation])
        if sample >= eps_threshold: 
            
            #action = q_values.max(1)[1] # First 1 is the dimension, second 1 is the index (this is argmax)
            action = q_values.argmax()
            
        else:
            action = np.random.randint(0,3)
        
            
        #break
        # Execute action in environment.
        old_state = observation
        if k%10000 == 0:
            print("q_values ")
            print(q_values)
            print("On state="+ str(observation) + ", selected action=" + str(action) + " , ")
        
        observation, reward, done, info = env.step(action) 
        new_state = observation
        
        # Store the transition in memory
        #memory.push(old_state, action, new_state, reward, done)

        
        if k%10000 == 0:
            print("new state="+ str(observation) + ", done="+str(done))
        #if done and reward != 1.0:
        #    reward = -1.0

        
        # Perform one step of the optimization (on the target network)
        q_value_new_state = np.array(q_function[new_state]).argmax()
        q_function[old_state][action] = q_function[old_state][action] + \
        ALPHA *( reward + (q_function[new_state][q_value_new_state] * GAMMA) - q_function[old_state][action])
        
    
        
   
    if len(score) < 100:
        score.append(reward)
    else:
        score[k % 100] = reward

    if k%1000 == 0:
        print("Episode {} finished after {} timesteps with r={}. Running score: {}. Times trained: {}. Times reached goal: {}.".format(k, len(episode_series), reward, np.mean(score), times_trained, times_reach_goal))
        times_trained = 0
        times_reach_goal = 0
  
    
    if reward > 0.0:
        times_reach_goal = times_reach_goal + 1

q_values 
[0. 0. 0. 0.]
On state=0, selected action=0 , 
new state=0, done=False
q_values 
[0. 0. 0. 0.]
On state=0, selected action=1 , 
new state=4, done=False
q_values 
[0. 0. 0. 0.]
On state=4, selected action=0 , 
new state=4, done=False
q_values 
[0. 0. 0. 0.]
On state=4, selected action=1 , 
new state=8, done=False
q_values 
[0. 0. 0. 0.]
On state=8, selected action=0 , 
new state=8, done=False
q_values 
[0. 0. 0. 0.]
On state=8, selected action=1 , 
new state=12, done=True
Episode 0 finished after 0 timesteps with r=0.0. Running score: 0.0. Times trained: 0. Times reached goal: 0.
Episode 1000 finished after 0 timesteps with r=0.0. Running score: 0.13. Times trained: 0. Times reached goal: 96.
Episode 2000 finished after 0 timesteps with r=1.0. Running score: 0.09. Times trained: 0. Times reached goal: 100.
Episode 3000 finished after 0 timesteps with r=0.0. Running score: 0.06. Times trained: 0. Times reached goal: 133.
Episode 4000 finished after 0 timesteps with r=0.0. Runni

Episode 54000 finished after 0 timesteps with r=0.0. Running score: 0.45. Times trained: 0. Times reached goal: 438.
Episode 55000 finished after 0 timesteps with r=0.0. Running score: 0.58. Times trained: 0. Times reached goal: 506.
Episode 56000 finished after 0 timesteps with r=0.0. Running score: 0.49. Times trained: 0. Times reached goal: 506.
Episode 57000 finished after 0 timesteps with r=1.0. Running score: 0.46. Times trained: 0. Times reached goal: 491.
Episode 58000 finished after 0 timesteps with r=0.0. Running score: 0.46. Times trained: 0. Times reached goal: 507.
Episode 59000 finished after 0 timesteps with r=1.0. Running score: 0.55. Times trained: 0. Times reached goal: 504.
q_values 
[0.531441 0.59049  0.59049  0.      ]
On state=0, selected action=0 , 
new state=0, done=False
q_values 
[0.531441 0.59049  0.59049  0.      ]
On state=0, selected action=1 , 
new state=4, done=False
q_values 
[0.59049 0.6561  0.      0.     ]
On state=4, selected action=0 , 
new state=4

Episode 102000 finished after 0 timesteps with r=1.0. Running score: 0.66. Times trained: 0. Times reached goal: 721.
Episode 103000 finished after 0 timesteps with r=1.0. Running score: 0.76. Times trained: 0. Times reached goal: 722.
Episode 104000 finished after 0 timesteps with r=1.0. Running score: 0.71. Times trained: 0. Times reached goal: 703.
Episode 105000 finished after 0 timesteps with r=1.0. Running score: 0.72. Times trained: 0. Times reached goal: 729.
Episode 106000 finished after 0 timesteps with r=0.0. Running score: 0.72. Times trained: 0. Times reached goal: 740.
Episode 107000 finished after 0 timesteps with r=1.0. Running score: 0.75. Times trained: 0. Times reached goal: 715.
Episode 108000 finished after 0 timesteps with r=1.0. Running score: 0.73. Times trained: 0. Times reached goal: 736.
Episode 109000 finished after 0 timesteps with r=1.0. Running score: 0.68. Times trained: 0. Times reached goal: 723.
q_values 
[0.531441 0.59049  0.59049  0.      ]
On state

Episode 152000 finished after 0 timesteps with r=1.0. Running score: 0.82. Times trained: 0. Times reached goal: 838.
Episode 153000 finished after 0 timesteps with r=1.0. Running score: 0.79. Times trained: 0. Times reached goal: 839.
Episode 154000 finished after 0 timesteps with r=1.0. Running score: 0.83. Times trained: 0. Times reached goal: 841.
Episode 155000 finished after 0 timesteps with r=1.0. Running score: 0.85. Times trained: 0. Times reached goal: 842.
Episode 156000 finished after 0 timesteps with r=1.0. Running score: 0.91. Times trained: 0. Times reached goal: 861.
Episode 157000 finished after 0 timesteps with r=1.0. Running score: 0.84. Times trained: 0. Times reached goal: 836.
Episode 158000 finished after 0 timesteps with r=1.0. Running score: 0.88. Times trained: 0. Times reached goal: 878.
Episode 159000 finished after 0 timesteps with r=1.0. Running score: 0.88. Times trained: 0. Times reached goal: 864.
q_values 
[0.531441 0.59049  0.59049  0.      ]
On state

Episode 203000 finished after 0 timesteps with r=1.0. Running score: 0.9. Times trained: 0. Times reached goal: 920.
Episode 204000 finished after 0 timesteps with r=1.0. Running score: 0.95. Times trained: 0. Times reached goal: 909.
Episode 205000 finished after 0 timesteps with r=1.0. Running score: 0.94. Times trained: 0. Times reached goal: 920.
Episode 206000 finished after 0 timesteps with r=1.0. Running score: 0.88. Times trained: 0. Times reached goal: 925.
Episode 207000 finished after 0 timesteps with r=1.0. Running score: 0.93. Times trained: 0. Times reached goal: 923.
Episode 208000 finished after 0 timesteps with r=1.0. Running score: 0.89. Times trained: 0. Times reached goal: 920.
Episode 209000 finished after 0 timesteps with r=1.0. Running score: 0.9. Times trained: 0. Times reached goal: 919.
q_values 
[0.531441 0.59049  0.59049  0.      ]
On state=0, selected action=1 , 
new state=4, done=False
q_values 
[0.59049 0.6561  0.      0.     ]
On state=4, selected action

Episode 251000 finished after 0 timesteps with r=1.0. Running score: 0.98. Times trained: 0. Times reached goal: 950.
Episode 252000 finished after 0 timesteps with r=1.0. Running score: 0.97. Times trained: 0. Times reached goal: 950.
Episode 253000 finished after 0 timesteps with r=1.0. Running score: 0.94. Times trained: 0. Times reached goal: 961.
Episode 254000 finished after 0 timesteps with r=1.0. Running score: 0.92. Times trained: 0. Times reached goal: 954.
Episode 255000 finished after 0 timesteps with r=1.0. Running score: 0.96. Times trained: 0. Times reached goal: 952.
Episode 256000 finished after 0 timesteps with r=0.0. Running score: 0.9. Times trained: 0. Times reached goal: 964.
Episode 257000 finished after 0 timesteps with r=1.0. Running score: 0.96. Times trained: 0. Times reached goal: 953.
Episode 258000 finished after 0 timesteps with r=1.0. Running score: 0.95. Times trained: 0. Times reached goal: 952.
Episode 259000 finished after 0 timesteps with r=1.0. Run

Episode 302000 finished after 0 timesteps with r=1.0. Running score: 0.96. Times trained: 0. Times reached goal: 974.
Episode 303000 finished after 0 timesteps with r=1.0. Running score: 0.93. Times trained: 0. Times reached goal: 974.
Episode 304000 finished after 0 timesteps with r=1.0. Running score: 0.99. Times trained: 0. Times reached goal: 972.
Episode 305000 finished after 0 timesteps with r=1.0. Running score: 0.94. Times trained: 0. Times reached goal: 964.
Episode 306000 finished after 0 timesteps with r=1.0. Running score: 0.98. Times trained: 0. Times reached goal: 974.
Episode 307000 finished after 0 timesteps with r=1.0. Running score: 0.98. Times trained: 0. Times reached goal: 975.
Episode 308000 finished after 0 timesteps with r=1.0. Running score: 0.97. Times trained: 0. Times reached goal: 970.
Episode 309000 finished after 0 timesteps with r=1.0. Running score: 0.98. Times trained: 0. Times reached goal: 970.
q_values 
[0.531441 0.59049  0.59049  0.      ]
On state

Episode 353000 finished after 0 timesteps with r=1.0. Running score: 0.99. Times trained: 0. Times reached goal: 991.
Episode 354000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 988.
Episode 355000 finished after 0 timesteps with r=1.0. Running score: 0.99. Times trained: 0. Times reached goal: 991.
Episode 356000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 982.
Episode 357000 finished after 0 timesteps with r=1.0. Running score: 0.99. Times trained: 0. Times reached goal: 985.
Episode 358000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 988.
Episode 359000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 987.
q_values 
[0.531441 0.59049  0.59049  0.      ]
On state=0, selected action=1 , 
new state=4, done=False
q_values 
[0.59049 0.6561  0.      0.     ]
On state=4, selected action=1

Episode 401000 finished after 0 timesteps with r=1.0. Running score: 0.96. Times trained: 0. Times reached goal: 992.
Episode 402000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 994.
Episode 403000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 991.
Episode 404000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 998.
Episode 405000 finished after 0 timesteps with r=1.0. Running score: 0.99. Times trained: 0. Times reached goal: 995.
Episode 406000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 997.
Episode 407000 finished after 0 timesteps with r=1.0. Running score: 0.98. Times trained: 0. Times reached goal: 991.
Episode 408000 finished after 0 timesteps with r=1.0. Running score: 0.99. Times trained: 0. Times reached goal: 995.
Episode 409000 finished after 0 timesteps with r=1.0. Runnin

Episode 452000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 994.
Episode 453000 finished after 0 timesteps with r=1.0. Running score: 0.98. Times trained: 0. Times reached goal: 995.
Episode 454000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 994.
Episode 455000 finished after 0 timesteps with r=1.0. Running score: 0.99. Times trained: 0. Times reached goal: 996.
Episode 456000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 996.
Episode 457000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 997.
Episode 458000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 994.
Episode 459000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 999.
q_values 
[0.531441 0.59049  0.59049  0.      ]
On state=0, se

Episode 503000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 998.
Episode 504000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 998.
Episode 505000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 1000.
Episode 506000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 1000.
Episode 507000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 996.
Episode 508000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 999.
Episode 509000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 995.
q_values 
[0.531441 0.59049  0.59049  0.      ]
On state=0, selected action=1 , 
new state=4, done=False
q_values 
[0.59049 0.6561  0.      0.     ]
On state=4, selected action=1 

Episode 553000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 999.
Episode 554000 finished after 0 timesteps with r=1.0. Running score: 0.99. Times trained: 0. Times reached goal: 999.
Episode 555000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 1000.
Episode 556000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 1000.
Episode 557000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 1000.
Episode 558000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 998.
Episode 559000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 999.
q_values 
[0.531441 0.59049  0.59049  0.      ]
On state=0, selected action=1 , 
new state=4, done=False
q_values 
[0.59049 0.6561  0.      0.     ]
On state=4, selected action=

Episode 601000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 999.
Episode 602000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 999.
Episode 603000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 998.
Episode 604000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 998.
Episode 605000 finished after 0 timesteps with r=1.0. Running score: 0.99. Times trained: 0. Times reached goal: 999.
Episode 606000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 999.
Episode 607000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 1000.
Episode 608000 finished after 0 timesteps with r=1.0. Running score: 1.0. Times trained: 0. Times reached goal: 998.
Episode 609000 finished after 0 timesteps with r=1.0. Running 

KeyboardInterrupt: 